.github/workflows/blank.yml
=> added blank.yml test config

.github/workflows/blank.yml, .gitignore, projectApp/package.json, projectApp/src/HTML/app.html, projectApp/src/Scene/startScene.ts, projectApp/src/app.ts, projectApp/test/csvTesting.ts, projectApp/webpack.config.cjs
=> Prototype scene

projectApp/src/Functions/UrlCSVReader.tsx
also added function documentation
=> refactored a foreach loop in UrlCSVHeaders to a some loop

projectApp/src/Functions/LocalCSVReader.tsx, projectApp/test/csvTesting.tsx
Updating LocalCSVReader.tsx, making it more efficient, properly handling errors and rejects, cleaning up code and added more testing.
=> Id1 code freeze local csv updates

projectApp/src/components/UrlCSVReader.tsx
=> made all Promise rejects into Errors, if they werent already

.gitignore, projectApp/README.md, projectApp/package-lock.json, projectApp/package.json, projectApp/src/README.md, projectApp/src/components/LocalCSVReader.tsx, projectApp/src/components/UrlCSVReader.tsx, projectApp/src/logging/README.md, projectApp/src/logging/elastic.js, projectApp/src/logging/logs.js, projectApp/test/README.md, projectApp/test/csvTesting.tsx, projectApp/tsconfig.app.json, projectApp/tsconfig.node.json
Logging using elastic and Winston for the program now operational.  Updated functions and unit testing to include logging.  A read me for running the logging.
=> Id1 code freeze spike logging completed, updated unit testing with logs

projectApp/package.json
I added the hosting option to the dev script
=> Hosting option added to dev script

.github/workflows/build-attest.yml
Hi folks. this is my attempt to add attestations to the CI/CD workflow.
=> add an attestation workflow

.github/workflows/build-attest.yml
ok, let's try this one. GH can't find tarball path
=> Add release tarball to test branch

projectApp/src/components/Graph_Components/GraphClass.tsx
Create a skeleton file for GraphClass with a constructor and a method that logs to the console to confirm the class is initialized.
=> Create the GraphClass for Graphs

projectApp/src/types/GraphInterface.tsx
Creates the Graph Interface, lists the necessary variables to be used by Graph components. Aims for modularity and adaptability.
regarding issue #72
=> Id2 dev gui: Pull request to add Graph interface

projectApp/eslint.config.js, projectApp/package-lock.json, projectApp/package.json, projectApp/src/App.tsx, projectApp/src/components/CSV_Readers/LocalCSVReader.tsx, projectApp/src/components/CSV_Readers/UrlCSVReader.tsx, projectApp/src/components/Graph_Components/Create2DPoint.tsx, projectApp/src/controller/GraphController.tsx, projectApp/src/controller/MainController.tsx, projectApp/src/logging/elastic.js, projectApp/src/models/CSVDataModel.tsx, projectApp/src/models/CSVReaderModel.tsx, projectApp/src/pages/Graph_Objects/Point2D.tsx, projectApp/src/types/CSVInterfaces.tsx, projectApp/test/csvTesting.tsx
Just a quick pull request for adding linter to ID2Dev, will also have some of my models for file readers update.
=> Id2 dev ui and refactor; making a pull request to add linter to ID2Dev branch

projectApp/src/components/Graph_Components/GraphClass.test.ts, projectApp/src/components/Graph_Components/GraphClass.tsx, projectApp/src/components/Graph_Components/GraphClass2.tsx
=> Update unit test for GraphClass

projectApp/src/components/Graph_Components/CreateTimeSeries.tsx, projectApp/src/components/Graph_Components/GraphClass.test.ts, projectApp/src/components/Graph_Components/GraphClass.tsx, projectApp/src/models/CSVDataObject.tsx, projectApp/src/types/GraphClass2Interface.tsx, projectApp/src/types/GraphInterface.tsx
Changed GraphInterface and Graph Class to handle less attributes and methods, added an interface for the Graph class2
issue 111
=> Refactoring and code restructuring for Graph Interface, Graph Class and creation of interface for GraphClass2

projectApp/src/components/Graph_Components/GraphClass.test.ts
Rewrite the unit tests for GraphClass.
=> Update unit tests for GraphClass (Refactored)

projectApp/src/components/CSV_Readers/LocalCSVReader.tsx, projectApp/src/components/CSV_Readers/UrlCSVReader.tsx, projectApp/src/controller/CSVController.tsx, projectApp/src/models/CSVDataObject.tsx, projectApp/src/models/CSVReaderModel.tsx, projectApp/src/pages/UI/BrowserUI.tsx, projectApp/src/pages/UI/DropdownUI.tsx
made sure NOT to alter any functionally, only changed around where logging and erroring occurs
also for html code it should only change the indentation (tabs) because i think it looks more readable
=> Id2 testing csv

Tests/2DGraph.feature, Tests/csvLoader.feature
Completed first attempt at the 2D graph gherkin file. Also updated the CSV loader gherkin file to mention an example url. If there is a better (or actual) URL to use in each file please let me know and I'll update the PR.
Thanks!!
=> 2D Graph Gherkin File

projectApp/src/HTML/app.html, projectApp/src/components/CSV_Readers/LocalCSVReader.tsx, projectApp/src/components/CSV_Readers/UrlCSVReader.tsx, projectApp/src/components/Graph_Components/Create2DPoint.tsx, projectApp/src/controller/CSVController.tsx, projectApp/src/controller/GraphController.tsx, projectApp/src/models/CSVDataObject.tsx, projectApp/src/models/CSVReaderModel.tsx
Added the documentations from "ID2Dev-Code-Documentation" to this branch. I added comments and removed unnecessary comments (like "//logger.error()").
=> Id2 dev freeze documentation

projectApp/src/components/Graph_Components/GraphClass.tsx, projectApp/test/GraphClass.test.ts
Update the invariants and history for the GraphClass specification, add error handling to GraphClass, and add additional unit tests for GraphClass.
=> Id2 dev freeze graph class unit test

Tests/2DGraph.feature, Tests/csvLoader.feature, projectApp/logs2dg.txt, projectApp/test/2DGraph.test.ts
First draft of my log tests for the 2D graph functionality. Right now it only contains checks for logs I wrote. 
Side note: the build errors should be there, correct? Since the log.txt file is empty?
=> ID2 Testing - 2D Graph Log Tests

Tests/csvLoader.feature, projectApp/src/logger-frontend.ts
Re-formatted the comments for the logger-frontend.ts
=> ID2-Testing: Logger-Frontend commenting

projectApp/src/components/Graph_Components/CreateEmbeddedGraph.tsx, projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
Currently working on implementing a 3D Embedded Graph skeleton. Made CreateEmbeddedGraph.tsx and started EmbeddedGraph.tsx.
Issue #156 
Incomplete; no testing yet. Manual tests will be run for these specific components.
> [!TIP]
> [!IMPORTANT]
=> ID3-3DGraph-EmbeddedGraph

.github/workflows/BuildandTest.yml, .github/workflows/firebase-hosting-pull-request.yml, projectApp/src/models/CSVReaderModel.tsx, projectApp/src/pages/UI/BrowserUI.tsx, projectApp/src/types/CSVInterfaces.tsx
1. removed refs to csv deletion
2. picked the proper target branch this time
160: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2025-team-1/issues/160
all vitest tests passed.
> [!TIP]
> [!IMPORTANT]
=> ID3-CSV-noDel

.github/workflows/BuildandTest.yml, projectApp/src/components/Csv_Components/CSVReaders.tsx, projectApp/tests/unit_tests/csvTesting.test.ts
updated csv readers to allow any filepath (only allow .csv or links that lead to .csv or contain the csv file)
also refactored csvTesting.test.ts, shouldnt affect output (probably unnecessary)
#154
changes of CSVReaders.tsx have been run through npm run test and all have returned expected results
also did npm run dev and played around in localhost, url and local file reader window worked as expected for valid and invalid files
> [!TIP]
> [!IMPORTANT]
=> Id3 csv loader update

projectApp/src/controller/GraphController.tsx
Added get() and push() functionality as well as generateEmbeddedGraph().
Issue #163 
None currently, waiting on further implementation.
> [!TIP]
> [!IMPORTANT]
=> ID3-3DGraph-GraphController

projectApp/src/controller/CSVController.tsx, projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx, projectApp/src/pages/Scene/MainScene.tsx
Linked the embedded graph into the program. It now gets created at the same time as the Time Series graph. Currently the actaul graph isn't displayed but a box appears stating that the embedded graph was created.
#174
I ran the program and confirmed that the object i expected to appear did appear.
> [!TIP]
> [!IMPORTANT]
=> Id3 3D graph linking

projectApp/src/App.tsx
Made the VR scene take up the whole screen.
No issue associated with this
Running the program and making sure that the ui changes didn't break anything
> [!TIP]
> [!IMPORTANT]
=> Minor UI Updates

Tests/embedded_graph.feature
Added "rendering of embedded graph" scenario.
> [!IMPORTANT]
=> Id3 testing gherkins.

projectApp/src/App.tsx, projectApp/src/components/Graph_Components/Create2DPoint.tsx, projectApp/src/components/Graph_Components/CreateTimeSeries.tsx, projectApp/src/pages/Graph_Elements/Point2D.tsx, projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx, projectApp/src/pages/Scene/InitScene.tsx, projectApp/src/pages/Scene/MainScene.tsx, projectApp/src/pages/Scene/TestScene.tsx, projectApp/src/pages/UI/BrowserUI.tsx
Created the Testscene in the view, it is attached to the camera and is a fullscreen overlay.
#158 
Seeing if the testscene follows the camera and is properly formatted in the program.
> [!TIP]
> [!IMPORTANT]
=> Id3 test scene view

projectApp/tests/logConfirmationTests/EmbeddedConfirmation.test.ts
Added log confirmation vitest file
#186 
These should pass after using the Embedded Graph
> [!TIP]
> [!IMPORTANT]
=> Id3 testing embedded log confirmation

.github/workflows/BuildandTest.yml, Tests/embedded_graph.feature, projectApp/package.json, projectApp/tests/smoke_tests/example.test.js
I created scripts to run unit, log confirmation and smoke tests separately. I left the main "test" script to be able to run all at once as well.
#193 
I made sure all tests passed using the regular "test" script from before, and then created the new scripts made sure those passed their individal tests then made sure they ran successfully through github actions when pushed.
> [!TIP]
> [!IMPORTANT]
=> Id4 test script spliting

Tests/smokeTest.feature
Created the first draft of the Smoke Test Gherkin file. I'm looking for feedback to check if this is what we're expecting for Smoke Tests or if there are different areas of the system that need to be covered by this.
Issue #225 
There isn't much to test with this, as its simply a guide for manual testing.
> [!TIP]
> [!IMPORTANT]
=> ID4 Smoke Tests - Smoke Test Gherkin

projectApp/src/components/Csv_Components/CSVDataObject.tsx, projectApp/src/components/Csv_Components/CSVReaders.tsx, projectApp/src/components/Graph_Components/Create2DPoint.tsx, projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx, projectApp/src/components/Graph_Components/GraphObject.tsx, projectApp/src/components/Graph_Components/PointObject.tsx, projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx, projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx, projectApp/src/components/Graph_Components/Points/Point2DObject.tsx, projectApp/src/components/Graph_Components/Points/Point3DObject.tsx, projectApp/src/components/Graph_Components/Points/PointObject.tsx, projectApp/src/components/Graph_Components/TimeSeriesGraphObject.tsx, projectApp/src/controller/CSVController.tsx, projectApp/src/controller/GraphController.tsx, projectApp/src/controller/MainController.tsx, projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx, projectApp/src/pages/Graph_Elements/Point2D.tsx, projectApp/src/pages/Graph_Elements/Point3D.tsx, projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx, projectApp/src/types/EmbeddedInterface.tsx, projectApp/src/types/GraphInterface.tsx, projectApp/src/types/GraphPointsInterfaces.ts, projectApp/src/types/PointInterface.tsx, projectApp/src/types/TimeSeriesGraphInterface.tsx, projectApp/tests/unit_tests/EmbeddedGraph.test.ts, projectApp/tests/unit_tests/GraphClass.test.ts, projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts, projectApp/tests/unit_tests/csvMockFS.test.ts, projectApp/tests/unit_tests/csvTesting.test.ts
Display a 3d axis representing the embedded graph in the scene.  Refactored graph files to display the 3d points.
#215 #213 
Passes the current Embedded graph tests. Manual testing to see if 3D points is within the axis while using the calculations made.
> [!TIP]
> [!IMPORTANT]
=> Id4 embedded graph vr points

projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx, projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx, projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx, projectApp/src/controller/MainController.tsx, projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx, projectApp/src/pages/Graph_Elements/Point2D.tsx, projectApp/src/pages/Graph_Elements/Point3D.tsx, projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
Linking and forming a relationship between the 2D and 3D points
#214 
Manually seeing if the points update together, passing tests to see if points share data
> [!TIP]
> [!IMPORTANT]
=> Id4 embedded graph link

projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
Ensure that the "Point Value" updates to reflect the correct dataset when a point in the graph is selected. Note that current "Point Value" component only supports single-point selection and will not update for multiple selections.
#196  #204 
> [!TIP]
> [!IMPORTANT]
=> Id4 bug fixes defect7

Tests/2DGraph.feature, Tests/csvLoader.feature, Tests/embedded_graph.feature, Tests/runningWebXR.feature
performed minor updates to 2dgraph, embedded graph gherkin files to reflect updates made for iD4 deliverable. Main change was to reflect additions of embedded graph in VR space, and removing ability to delete a graph from the 2d space. I believe I also adjusted the spacing in the runningwebxr file.
https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2025-team-1/issues/230
ran gherkin linter command. fixed typo errors
> [!TIP]
> [!IMPORTANT]
=> updated gherkin files to reflect changes in test environment

projectApp/src/App.tsx, projectApp/src/controller/Locomotion.tsx
implemented a Locomotion component that allows the right controller joystick to move the user relative to facing direction
#261 
1. execute npm run dev
2. enter vr
3. make sure the graph block is visible to determine if movement occurs
4. without turning camera, use the right joystick (if in browser use arrow keys) to move clockwise: forward, right, backwards, then left
5. then do it counterclockwise
6. then turning about 90 degrees to the right and repeat steps 4 and 5, make sure the graph block is visible to determine if movement occurs
7. repeat step 6 two more times for 180 and 270 degrees
8. then try continuous movement while turning the camera and 
Should expect the user to move 
> [!TIP]
> …
=> Id5 features movement

projectApp/tests/unit_tests/PointObjects.test.ts
Add unit tests for the Point2DObject and Point3DObject, and improve their coverage to 100%.
#270 
> [!TIP]
> [!IMPORTANT]
=> Id5 testing unittests point objects

projectApp/src/components/Csv_Components/CSVDataObject.ts, projectApp/src/controller/CSVController.ts, projectApp/src/pages/UI/DropdownUI.tsx, projectApp/tests/smoke_tests/graph.test.ts, projectApp/tests/unit_tests/csvDataObject.test.ts
Added an option for first differencing of the data before generating a graph. Also added in more unit test coverage for the CSVDataObject.
#263 and #272 
Created unit tests for the first differencing functions, and ran the program and confirmed that the first differencing acted as expected
> [!TIP]
> [!IMPORTANT]
=> Id5 features first differencing

projectApp/src/pages/UI/DropdownUI.tsx
Added some info to the Info Box! Let me know if there are any suggestions to improve it!
Issue #259 
Just running the code and using different CSVs!
> [!TIP]
> [!IMPORTANT]
=> ID5-Features: DDInfoBox

Tests/embedded_graph.feature
… files and the other is for using URL-based CSV files)
Separated one scenario to two different scenarios. One for using local CSV file and the other is for using UML-based CSV file.
> [!IMPORTANT]
=> Made two seperate scenarios for 

projectApp/src/components/Csv_Components/CSVDataObject.ts, projectApp/src/components/Graph_Components/GraphObject.ts, projectApp/src/controller/CSVController.ts, projectApp/src/models/CSVReaderModel.ts, projectApp/src/pages/UI/BrowserUI.tsx, projectApp/src/types/BaseInterfaces.ts, projectApp/src/types/CSVInterfaces.ts, projectApp/src/types/GraphInterface.ts, projectApp/tests/unit_tests/CSVController.test.ts, projectApp/tests/unit_tests/GraphClass.test.ts
Added more checks for invalid csv files in order to avoid broken graphs and an unexpected header being loaded.
#296 #288 
If the program properly denies invalid csv files and throws an error.  If it passes existing csv loading tests to ensure the same expected functionality occurs.
> [!TIP]
> [!IMPORTANT]
=> Defect #21 & #29 fix: Invalid CSV Files

projectApp/src/controller/CSVController.ts, projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx, projectApp/src/pages/UI/DropdownUI.tsx
Moved the header selection feature from the Time Series Graph to the drop down ui component. This feature still functions similarly but is just located in a different location.
#305 
Ran through manual tests and confirmed that everything works as expected and confirmed that all automated tests pass.
> [!TIP]
> [!IMPORTANT]
=> Id5 features header selection

projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Added some more unit tests to increase coverage for the TimeSeriesGraphObject
Issue #269 
Just running the tests using npm!
> [!TIP]
> [!IMPORTANT]
=> ID5-UnitTests-TimeSeriesGraphObject

projectApp/src/pages/UI/DropdownUI.tsx
Fixed not being able to press the buttons on the DropDownUI while in VR.
#290 
Ran the program and confirmed that the buttons could be pressed.
> [!TIP]
> [!IMPORTANT]
=> fixed controller not hitting buttons on dropdownUI while in vr

projectApp/tests/unit_tests/CSVReaderModel.test.ts
Add unit tests for CSVReaderModel to improve the test coverage.
#315 
> [!TIP]
> [!IMPORTANT]
=> Id5 unit tests csv reader model

projectApp/tests/unit_tests/CSVController.test.ts
Update CSVController unit tests to improve test coverage
#316 
> [!TIP]
> [!IMPORTANT]
=> Update CSVController unit tests to improve test coverage

Tests/2DGraph.feature, projectApp/tests/logConfirmationTests/2DGraph.test.ts, projectApp/tests/logConfirmationTests/EmbeddedConfirmation.test.ts
Updated log confirmation tests, both graphs now tests for first differencing logs
#321 
Manually test by following Gherkins steps, store the logs and use it to replace the log confirmation text file, update log confirmation tests to include first differencing logs
> [!TIP]
> [!IMPORTANT]
=> Id5 log confirmation

projectApp/src/components/Graph_Components/EmbeddedGraphObject.ts, projectApp/src/components/Graph_Components/TimeSeriesGraphObject.ts, projectApp/src/controller/GraphController.ts
Fixing the defect where the Y-axis of the time series graph does not update on first differencing. Additions to first diff effect on graphs, index for 2d x-axis and 3D graph are now also affected by first diff.
#291 
If the data value of selected point matches the points position in the graph in relation to other points.
> [!TIP]
> [!IMPORTANT]
=> Id5 f dif graph changes

projectApp/src/types/CSVInterfaces.ts, projectApp/src/types/EmbeddedInterface.ts, projectApp/src/types/GraphInterface.ts, projectApp/src/types/TimeSeriesGraphInterface.ts
Checked each of the interfaces and updated as needed to include missing functions/comments etc.
Issue #318 
None for this specific task!
> [!TIP]
> [!IMPORTANT]
=> ID5 - Interface Fixes

projectApp/src/components/Csv_Components/CSVDataObject.ts, projectApp/src/components/Graph_Components/GraphObject.ts, projectApp/tests/unit_tests/GraphClass.test.ts
Update assert in CSVDataObject and GraphObject, and update the unit tests
#281 
> [!TIP]
> [!IMPORTANT]
=> Id5 assertion apr4
